services:
  - type: web
    name: stock-lighthouse
    runtime: python
    plan: free
    rootDir: stock_lighthouse
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
